# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_designs\Ui_localization_fullHD.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/figures/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_bckgrd = QtWidgets.QFrame(self.centralwidget)
        self.frame_bckgrd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_bckgrd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bckgrd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bckgrd.setObjectName("frame_bckgrd")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_bckgrd)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_imec_logo = QtWidgets.QFrame(self.frame_bckgrd)
        self.frame_imec_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imec_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imec_logo.setObjectName("frame_imec_logo")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_imec_logo)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_logo_jade = QtWidgets.QLabel(self.frame_imec_logo)
        self.label_logo_jade.setMinimumSize(QtCore.QSize(200, 60))
        self.label_logo_jade.setMaximumSize(QtCore.QSize(200, 60))
        self.label_logo_jade.setStyleSheet("")
        self.label_logo_jade.setText("")
        self.label_logo_jade.setPixmap(QtGui.QPixmap(":/Figures/figures/imec-logo_200x60.png"))
        self.label_logo_jade.setObjectName("label_logo_jade")
        self.gridLayout_3.addWidget(self.label_logo_jade, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_imec_logo, 0, 0, 1, 1)
        self.frame_title = QtWidgets.QFrame(self.frame_bckgrd)
        self.frame_title.setMinimumSize(QtCore.QSize(800, 0))
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.label_title = QtWidgets.QLabel(self.frame_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAutoFillBackground(False)
        self.label_title.setStyleSheet("color: rgb(144, 41, 141);")
        self.label_title.setTextFormat(QtCore.Qt.PlainText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_title, 0, 1, 1, 1)
        self.frame_data1 = QtWidgets.QFrame(self.frame_bckgrd)
        self.frame_data1.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_data1.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_data1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_data1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_data1.setObjectName("frame_data1")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_data1)
        self.gridLayout.setObjectName("gridLayout")
        self.cosic_logo_layout = QtWidgets.QHBoxLayout()
        self.cosic_logo_layout.setObjectName("cosic_logo_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cosic_logo_layout.addItem(spacerItem2)
        self.label_logocosic_jade = QtWidgets.QLabel(self.frame_data1)
        self.label_logocosic_jade.setMinimumSize(QtCore.QSize(132, 174))
        self.label_logocosic_jade.setMaximumSize(QtCore.QSize(132, 174))
        self.label_logocosic_jade.setStyleSheet("")
        self.label_logocosic_jade.setText("")
        self.label_logocosic_jade.setPixmap(QtGui.QPixmap(":/Figures/figures/cosic_logo.png"))
        self.label_logocosic_jade.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logocosic_jade.setObjectName("label_logocosic_jade")
        self.cosic_logo_layout.addWidget(self.label_logocosic_jade)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cosic_logo_layout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.cosic_logo_layout, 0, 0, 1, 1)
        self.dist_layout_name = QtWidgets.QHBoxLayout()
        self.dist_layout_name.setObjectName("dist_layout_name")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dist_layout_name.addItem(spacerItem4)
        self.label_distance = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_distance.sizePolicy().hasHeightForWidth())
        self.label_distance.setSizePolicy(sizePolicy)
        self.label_distance.setMinimumSize(QtCore.QSize(100, 24))
        self.label_distance.setMaximumSize(QtCore.QSize(300, 24))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.label_distance.setFont(font)
        self.label_distance.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_distance.setTextFormat(QtCore.Qt.PlainText)
        self.label_distance.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_distance.setObjectName("label_distance")
        self.dist_layout_name.addWidget(self.label_distance)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dist_layout_name.addItem(spacerItem5)
        self.gridLayout.addLayout(self.dist_layout_name, 1, 0, 1, 1)
        self.distance_display_layout = QtWidgets.QHBoxLayout()
        self.distance_display_layout.setObjectName("distance_display_layout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.distance_display_layout.addItem(spacerItem6)
        self.lcdNumber_jade_MCIQdist = QtWidgets.QLCDNumber(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_jade_MCIQdist.sizePolicy().hasHeightForWidth())
        self.lcdNumber_jade_MCIQdist.setSizePolicy(sizePolicy)
        self.lcdNumber_jade_MCIQdist.setMinimumSize(QtCore.QSize(170, 70))
        self.lcdNumber_jade_MCIQdist.setMaximumSize(QtCore.QSize(200, 70))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.lcdNumber_jade_MCIQdist.setFont(font)
        self.lcdNumber_jade_MCIQdist.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcdNumber_jade_MCIQdist.setSmallDecimalPoint(True)
        self.lcdNumber_jade_MCIQdist.setDigitCount(4)
        self.lcdNumber_jade_MCIQdist.setMode(QtWidgets.QLCDNumber.Oct)
        self.lcdNumber_jade_MCIQdist.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_jade_MCIQdist.setProperty("value", 0.0)
        self.lcdNumber_jade_MCIQdist.setProperty("intValue", 0)
        self.lcdNumber_jade_MCIQdist.setObjectName("lcdNumber_jade_MCIQdist")
        self.distance_display_layout.addWidget(self.lcdNumber_jade_MCIQdist)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.distance_display_layout.addItem(spacerItem7)
        self.gridLayout.addLayout(self.distance_display_layout, 2, 0, 1, 1)
        self.angle_layout_name = QtWidgets.QHBoxLayout()
        self.angle_layout_name.setObjectName("angle_layout_name")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.angle_layout_name.addItem(spacerItem8)
        self.label_angle = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_angle.sizePolicy().hasHeightForWidth())
        self.label_angle.setSizePolicy(sizePolicy)
        self.label_angle.setMinimumSize(QtCore.QSize(121, 24))
        self.label_angle.setMaximumSize(QtCore.QSize(300, 24))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.label_angle.setFont(font)
        self.label_angle.setAutoFillBackground(False)
        self.label_angle.setTextFormat(QtCore.Qt.PlainText)
        self.label_angle.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_angle.setObjectName("label_angle")
        self.angle_layout_name.addWidget(self.label_angle)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.angle_layout_name.addItem(spacerItem9)
        self.gridLayout.addLayout(self.angle_layout_name, 3, 0, 1, 1)
        self.angle_display_layout = QtWidgets.QHBoxLayout()
        self.angle_display_layout.setObjectName("angle_display_layout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.angle_display_layout.addItem(spacerItem10)
        self.lcdNumber_jade_aoa = QtWidgets.QLCDNumber(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_jade_aoa.sizePolicy().hasHeightForWidth())
        self.lcdNumber_jade_aoa.setSizePolicy(sizePolicy)
        self.lcdNumber_jade_aoa.setMinimumSize(QtCore.QSize(170, 70))
        self.lcdNumber_jade_aoa.setMaximumSize(QtCore.QSize(170, 70))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.lcdNumber_jade_aoa.setFont(font)
        self.lcdNumber_jade_aoa.setSmallDecimalPoint(True)
        self.lcdNumber_jade_aoa.setDigitCount(4)
        self.lcdNumber_jade_aoa.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_jade_aoa.setProperty("value", 0.0)
        self.lcdNumber_jade_aoa.setProperty("intValue", 0)
        self.lcdNumber_jade_aoa.setObjectName("lcdNumber_jade_aoa")
        self.angle_display_layout.addWidget(self.lcdNumber_jade_aoa)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.angle_display_layout.addItem(spacerItem11)
        self.gridLayout.addLayout(self.angle_display_layout, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_likeliness = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_likeliness.sizePolicy().hasHeightForWidth())
        self.label_likeliness.setSizePolicy(sizePolicy)
        self.label_likeliness.setMinimumSize(QtCore.QSize(0, 0))
        self.label_likeliness.setMaximumSize(QtCore.QSize(125, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.label_likeliness.setFont(font)
        self.label_likeliness.setAutoFillBackground(False)
        self.label_likeliness.setTextFormat(QtCore.Qt.PlainText)
        self.label_likeliness.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_likeliness.setObjectName("label_likeliness")
        self.horizontalLayout.addWidget(self.label_likeliness)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.likeliness_textEdit = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.likeliness_textEdit.sizePolicy().hasHeightForWidth())
        self.likeliness_textEdit.setSizePolicy(sizePolicy)
        self.likeliness_textEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.likeliness_textEdit.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.likeliness_textEdit.setFont(font)
        self.likeliness_textEdit.setAcceptDrops(False)
        self.likeliness_textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.likeliness_textEdit.setStyleSheet("")
        self.likeliness_textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.likeliness_textEdit.setLineWidth(0)
        self.likeliness_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.likeliness_textEdit.setReadOnly(True)
        self.likeliness_textEdit.setAcceptRichText(True)
        self.likeliness_textEdit.setObjectName("likeliness_textEdit")
        self.horizontalLayout.addWidget(self.likeliness_textEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RSSI_label = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RSSI_label.sizePolicy().hasHeightForWidth())
        self.RSSI_label.setSizePolicy(sizePolicy)
        self.RSSI_label.setMinimumSize(QtCore.QSize(0, 0))
        self.RSSI_label.setMaximumSize(QtCore.QSize(125, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.RSSI_label.setFont(font)
        self.RSSI_label.setObjectName("RSSI_label")
        self.horizontalLayout_2.addWidget(self.RSSI_label)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.RSSI_textEdit = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RSSI_textEdit.sizePolicy().hasHeightForWidth())
        self.RSSI_textEdit.setSizePolicy(sizePolicy)
        self.RSSI_textEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.RSSI_textEdit.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RSSI_textEdit.setFont(font)
        self.RSSI_textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RSSI_textEdit.setStyleSheet("")
        self.RSSI_textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RSSI_textEdit.setLineWidth(0)
        self.RSSI_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RSSI_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RSSI_textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.RSSI_textEdit.setObjectName("RSSI_textEdit")
        self.horizontalLayout_2.addWidget(self.RSSI_textEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ToF_label = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToF_label.sizePolicy().hasHeightForWidth())
        self.ToF_label.setSizePolicy(sizePolicy)
        self.ToF_label.setMinimumSize(QtCore.QSize(0, 0))
        self.ToF_label.setMaximumSize(QtCore.QSize(125, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.ToF_label.setFont(font)
        self.ToF_label.setObjectName("ToF_label")
        self.horizontalLayout_3.addWidget(self.ToF_label)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.ToF_textEdit = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToF_textEdit.sizePolicy().hasHeightForWidth())
        self.ToF_textEdit.setSizePolicy(sizePolicy)
        self.ToF_textEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.ToF_textEdit.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ToF_textEdit.setFont(font)
        self.ToF_textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToF_textEdit.setStyleSheet("")
        self.ToF_textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ToF_textEdit.setLineWidth(0)
        self.ToF_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ToF_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ToF_textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.ToF_textEdit.setObjectName("ToF_textEdit")
        self.horizontalLayout_3.addWidget(self.ToF_textEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ToF_label_2 = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToF_label_2.sizePolicy().hasHeightForWidth())
        self.ToF_label_2.setSizePolicy(sizePolicy)
        self.ToF_label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.ToF_label_2.setMaximumSize(QtCore.QSize(115, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.ToF_label_2.setFont(font)
        self.ToF_label_2.setObjectName("ToF_label_2")
        self.horizontalLayout_4.addWidget(self.ToF_label_2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.vel_textEdit = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vel_textEdit.sizePolicy().hasHeightForWidth())
        self.vel_textEdit.setSizePolicy(sizePolicy)
        self.vel_textEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.vel_textEdit.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vel_textEdit.setFont(font)
        self.vel_textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vel_textEdit.setStyleSheet("")
        self.vel_textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vel_textEdit.setLineWidth(0)
        self.vel_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vel_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vel_textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.vel_textEdit.setObjectName("vel_textEdit")
        self.horizontalLayout_4.addWidget(self.vel_textEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame_data1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 9, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.connection_label = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_label.sizePolicy().hasHeightForWidth())
        self.connection_label.setSizePolicy(sizePolicy)
        self.connection_label.setMinimumSize(QtCore.QSize(105, 25))
        self.connection_label.setMaximumSize(QtCore.QSize(105, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.connection_label.setFont(font)
        self.connection_label.setObjectName("connection_label")
        self.horizontalLayout_5.addWidget(self.connection_label)
        self.connection_led = QtWidgets.QHBoxLayout()
        self.connection_led.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.connection_led.setSpacing(0)
        self.connection_led.setObjectName("connection_led")
        self.horizontalLayout_5.addLayout(self.connection_led)
        self.gridLayout.addLayout(self.horizontalLayout_5, 10, 0, 1, 1)
        self.security_layout = QtWidgets.QHBoxLayout()
        self.security_layout.setObjectName("security_layout")
        self.authentication_label = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authentication_label.sizePolicy().hasHeightForWidth())
        self.authentication_label.setSizePolicy(sizePolicy)
        self.authentication_label.setMinimumSize(QtCore.QSize(105, 25))
        self.authentication_label.setMaximumSize(QtCore.QSize(105, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.authentication_label.setFont(font)
        self.authentication_label.setObjectName("authentication_label")
        self.security_layout.addWidget(self.authentication_label)
        self.authentication_led = QtWidgets.QHBoxLayout()
        self.authentication_led.setSpacing(6)
        self.authentication_led.setObjectName("authentication_led")
        self.security_layout.addLayout(self.authentication_led)
        self.gridLayout.addLayout(self.security_layout, 11, 0, 1, 1)
        self.authorization_layout = QtWidgets.QHBoxLayout()
        self.authorization_layout.setObjectName("authorization_layout")
        self.circleoftrust_label = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circleoftrust_label.sizePolicy().hasHeightForWidth())
        self.circleoftrust_label.setSizePolicy(sizePolicy)
        self.circleoftrust_label.setMinimumSize(QtCore.QSize(105, 25))
        self.circleoftrust_label.setMaximumSize(QtCore.QSize(105, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.circleoftrust_label.setFont(font)
        self.circleoftrust_label.setObjectName("circleoftrust_label")
        self.authorization_layout.addWidget(self.circleoftrust_label)
        self.circleoftrust_led = QtWidgets.QHBoxLayout()
        self.circleoftrust_led.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.circleoftrust_led.setSpacing(6)
        self.circleoftrust_led.setObjectName("circleoftrust_led")
        self.authorization_layout.addLayout(self.circleoftrust_led)
        self.gridLayout.addLayout(self.authorization_layout, 12, 0, 1, 1)
        self.start_button_layout = QtWidgets.QHBoxLayout()
        self.start_button_layout.setObjectName("start_button_layout")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.start_button_layout.addItem(spacerItem16)
        self.btnStart_jade = QtWidgets.QPushButton(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart_jade.sizePolicy().hasHeightForWidth())
        self.btnStart_jade.setSizePolicy(sizePolicy)
        self.btnStart_jade.setMinimumSize(QtCore.QSize(159, 55))
        self.btnStart_jade.setMaximumSize(QtCore.QSize(159, 55))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart_jade.setFont(font)
        self.btnStart_jade.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/figures/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/Icons/figures/Stop.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.btnStart_jade.setIcon(icon1)
        self.btnStart_jade.setObjectName("btnStart_jade")
        self.start_button_layout.addWidget(self.btnStart_jade)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.start_button_layout.addItem(spacerItem17)
        self.gridLayout.addLayout(self.start_button_layout, 13, 0, 1, 1)
        self.exit_button_layout = QtWidgets.QHBoxLayout()
        self.exit_button_layout.setObjectName("exit_button_layout")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.exit_button_layout.addItem(spacerItem18)
        self.btnExit_jade = QtWidgets.QPushButton(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit_jade.sizePolicy().hasHeightForWidth())
        self.btnExit_jade.setSizePolicy(sizePolicy)
        self.btnExit_jade.setMinimumSize(QtCore.QSize(159, 55))
        self.btnExit_jade.setMaximumSize(QtCore.QSize(159, 55))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit_jade.setFont(font)
        self.btnExit_jade.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/figures/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit_jade.setIcon(icon2)
        self.btnExit_jade.setObjectName("btnExit_jade")
        self.exit_button_layout.addWidget(self.btnExit_jade)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.exit_button_layout.addItem(spacerItem19)
        self.gridLayout.addLayout(self.exit_button_layout, 14, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem20, 15, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_data1, 1, 0, 1, 1)
        self.MplWidget = MplWidget(self.frame_bckgrd)
        self.MplWidget.setMinimumSize(QtCore.QSize(800, 450))
        self.MplWidget.setMaximumSize(QtCore.QSize(1600, 900))
        self.MplWidget.setStyleSheet("")
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout_4.addWidget(self.MplWidget, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_bckgrd, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "imec - Passive keyless entry using Bluetooth"))
        self.label_title.setText(_translate("MainWindow", "Passive keyless entry using Bluetooth"))
        self.label_distance.setText(_translate("MainWindow", "Distance (m)"))
        self.label_angle.setText(_translate("MainWindow", "Angle (degrees)"))
        self.label_likeliness.setText(_translate("MainWindow", "Likeliness"))
        self.likeliness_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.RSSI_label.setText(_translate("MainWindow", "RSSI (dBm)"))
        self.RSSI_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ToF_label.setText(_translate("MainWindow", "ToF Distance (m)"))
        self.ToF_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ToF_label_2.setText(_translate("MainWindow", "Velocity (m/s)"))
        self.vel_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.connection_label.setText(_translate("MainWindow", "Connection"))
        self.authentication_label.setText(_translate("MainWindow", "Authentication"))
        self.circleoftrust_label.setText(_translate("MainWindow", "Circle of trust"))
        self.btnStart_jade.setText(_translate("MainWindow", "Start"))
        self.btnExit_jade.setText(_translate("MainWindow", "Exit"))
from mplwidget import MplWidget
import gui_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
