# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _ranging
else:
    import _ranging

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ranging.delete_SwigPyIterator

    def value(self):
        return _ranging.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ranging.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ranging.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ranging.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ranging.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ranging.SwigPyIterator_copy(self)

    def next(self):
        return _ranging.SwigPyIterator_next(self)

    def __next__(self):
        return _ranging.SwigPyIterator___next__(self)

    def previous(self):
        return _ranging.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ranging.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ranging.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ranging.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ranging.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ranging.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ranging.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ranging.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ranging:
_ranging.SwigPyIterator_swigregister(SwigPyIterator)

class Integer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _ranging.Integer_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ranging.Integer___nonzero__(self)

    def __bool__(self):
        return _ranging.Integer___bool__(self)

    def __len__(self):
        return _ranging.Integer___len__(self)

    def __getslice__(self, i, j):
        return _ranging.Integer___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ranging.Integer___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ranging.Integer___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ranging.Integer___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ranging.Integer___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ranging.Integer___setitem__(self, *args)

    def pop(self):
        return _ranging.Integer_pop(self)

    def append(self, x):
        return _ranging.Integer_append(self, x)

    def empty(self):
        return _ranging.Integer_empty(self)

    def size(self):
        return _ranging.Integer_size(self)

    def swap(self, v):
        return _ranging.Integer_swap(self, v)

    def begin(self):
        return _ranging.Integer_begin(self)

    def end(self):
        return _ranging.Integer_end(self)

    def rbegin(self):
        return _ranging.Integer_rbegin(self)

    def rend(self):
        return _ranging.Integer_rend(self)

    def clear(self):
        return _ranging.Integer_clear(self)

    def get_allocator(self):
        return _ranging.Integer_get_allocator(self)

    def pop_back(self):
        return _ranging.Integer_pop_back(self)

    def erase(self, *args):
        return _ranging.Integer_erase(self, *args)

    def __init__(self, *args):
        _ranging.Integer_swiginit(self, _ranging.new_Integer(*args))

    def push_back(self, x):
        return _ranging.Integer_push_back(self, x)

    def front(self):
        return _ranging.Integer_front(self)

    def back(self):
        return _ranging.Integer_back(self)

    def assign(self, n, x):
        return _ranging.Integer_assign(self, n, x)

    def resize(self, *args):
        return _ranging.Integer_resize(self, *args)

    def insert(self, *args):
        return _ranging.Integer_insert(self, *args)

    def reserve(self, n):
        return _ranging.Integer_reserve(self, n)

    def capacity(self):
        return _ranging.Integer_capacity(self)
    __swig_destroy__ = _ranging.delete_Integer

# Register Integer in _ranging:
_ranging.Integer_swigregister(Integer)

class Float(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _ranging.Float_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ranging.Float___nonzero__(self)

    def __bool__(self):
        return _ranging.Float___bool__(self)

    def __len__(self):
        return _ranging.Float___len__(self)

    def __getslice__(self, i, j):
        return _ranging.Float___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ranging.Float___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ranging.Float___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ranging.Float___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ranging.Float___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ranging.Float___setitem__(self, *args)

    def pop(self):
        return _ranging.Float_pop(self)

    def append(self, x):
        return _ranging.Float_append(self, x)

    def empty(self):
        return _ranging.Float_empty(self)

    def size(self):
        return _ranging.Float_size(self)

    def swap(self, v):
        return _ranging.Float_swap(self, v)

    def begin(self):
        return _ranging.Float_begin(self)

    def end(self):
        return _ranging.Float_end(self)

    def rbegin(self):
        return _ranging.Float_rbegin(self)

    def rend(self):
        return _ranging.Float_rend(self)

    def clear(self):
        return _ranging.Float_clear(self)

    def get_allocator(self):
        return _ranging.Float_get_allocator(self)

    def pop_back(self):
        return _ranging.Float_pop_back(self)

    def erase(self, *args):
        return _ranging.Float_erase(self, *args)

    def __init__(self, *args):
        _ranging.Float_swiginit(self, _ranging.new_Float(*args))

    def push_back(self, x):
        return _ranging.Float_push_back(self, x)

    def front(self):
        return _ranging.Float_front(self)

    def back(self):
        return _ranging.Float_back(self)

    def assign(self, n, x):
        return _ranging.Float_assign(self, n, x)

    def resize(self, *args):
        return _ranging.Float_resize(self, *args)

    def insert(self, *args):
        return _ranging.Float_insert(self, *args)

    def reserve(self, n):
        return _ranging.Float_reserve(self, n)

    def capacity(self):
        return _ranging.Float_capacity(self)
    __swig_destroy__ = _ranging.delete_Float

# Register Float in _ranging:
_ranging.Float_swigregister(Float)

class Complex(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def iterator(self):
        return _ranging.Complex_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ranging.Complex___nonzero__(self)

    def __bool__(self):
        return _ranging.Complex___bool__(self)

    def __len__(self):
        return _ranging.Complex___len__(self)

    def __getslice__(self, i, j):
        return _ranging.Complex___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ranging.Complex___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ranging.Complex___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ranging.Complex___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ranging.Complex___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ranging.Complex___setitem__(self, *args)

    def pop(self):
        return _ranging.Complex_pop(self)

    def append(self, x):
        return _ranging.Complex_append(self, x)

    def empty(self):
        return _ranging.Complex_empty(self)

    def size(self):
        return _ranging.Complex_size(self)

    def swap(self, v):
        return _ranging.Complex_swap(self, v)

    def begin(self):
        return _ranging.Complex_begin(self)

    def end(self):
        return _ranging.Complex_end(self)

    def rbegin(self):
        return _ranging.Complex_rbegin(self)

    def rend(self):
        return _ranging.Complex_rend(self)

    def clear(self):
        return _ranging.Complex_clear(self)

    def get_allocator(self):
        return _ranging.Complex_get_allocator(self)

    def pop_back(self):
        return _ranging.Complex_pop_back(self)

    def erase(self, *args):
        return _ranging.Complex_erase(self, *args)

    def __init__(self, *args):
        _ranging.Complex_swiginit(self, _ranging.new_Complex(*args))

    def push_back(self, x):
        return _ranging.Complex_push_back(self, x)

    def front(self):
        return _ranging.Complex_front(self)

    def back(self):
        return _ranging.Complex_back(self)

    def assign(self, n, x):
        return _ranging.Complex_assign(self, n, x)

    def resize(self, *args):
        return _ranging.Complex_resize(self, *args)

    def insert(self, *args):
        return _ranging.Complex_insert(self, *args)

    def reserve(self, n):
        return _ranging.Complex_reserve(self, n)

    def capacity(self):
        return _ranging.Complex_capacity(self)
    __swig_destroy__ = _ranging.delete_Complex

# Register Complex in _ranging:
_ranging.Complex_swigregister(Complex)

class CmplxMatrixType(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, _rows, _cols):
        _ranging.CmplxMatrixType_swiginit(self, _ranging.new_CmplxMatrixType(_rows, _cols))

    def size(self):
        return _ranging.CmplxMatrixType_size(self)

    def rows(self):
        return _ranging.CmplxMatrixType_rows(self)

    def cols(self):
        return _ranging.CmplxMatrixType_cols(self)

    def resize(self, _rows, _cols):
        return _ranging.CmplxMatrixType_resize(self, _rows, _cols)
    data = property(_ranging.CmplxMatrixType_data_get, _ranging.CmplxMatrixType_data_set)
    __swig_destroy__ = _ranging.delete_CmplxMatrixType

# Register CmplxMatrixType in _ranging:
_ranging.CmplxMatrixType_swigregister(CmplxMatrixType)

class DataPhMag(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, _rows, _cols):
        _ranging.DataPhMag_swiginit(self, _ranging.new_DataPhMag(_rows, _cols))

    def size(self):
        return _ranging.DataPhMag_size(self)
    phaseA = property(_ranging.DataPhMag_phaseA_get, _ranging.DataPhMag_phaseA_set)
    phaseB = property(_ranging.DataPhMag_phaseB_get, _ranging.DataPhMag_phaseB_set)
    magnitudeA = property(_ranging.DataPhMag_magnitudeA_get, _ranging.DataPhMag_magnitudeA_set)
    magnitudeB = property(_ranging.DataPhMag_magnitudeB_get, _ranging.DataPhMag_magnitudeB_set)
    H_est = property(_ranging.DataPhMag_H_est_get, _ranging.DataPhMag_H_est_set)

    def rows(self):
        return _ranging.DataPhMag_rows(self)

    def cols(self):
        return _ranging.DataPhMag_cols(self)
    __swig_destroy__ = _ranging.delete_DataPhMag

# Register DataPhMag in _ranging:
_ranging.DataPhMag_swigregister(DataPhMag)

class DataIQ(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, _rows, _cols):
        _ranging.DataIQ_swiginit(self, _ranging.new_DataIQ(_rows, _cols))

    def size(self):
        return _ranging.DataIQ_size(self)
    IQ_A = property(_ranging.DataIQ_IQ_A_get, _ranging.DataIQ_IQ_A_set)
    IQ_B = property(_ranging.DataIQ_IQ_B_get, _ranging.DataIQ_IQ_B_set)
    H_est = property(_ranging.DataIQ_H_est_get, _ranging.DataIQ_H_est_set)
    Kest = property(_ranging.DataIQ_Kest_get, _ranging.DataIQ_Kest_set)
    Uncertainty = property(_ranging.DataIQ_Uncertainty_get, _ranging.DataIQ_Uncertainty_set)

    def rows(self):
        return _ranging.DataIQ_rows(self)

    def cols(self):
        return _ranging.DataIQ_cols(self)
    __swig_destroy__ = _ranging.delete_DataIQ

# Register DataIQ in _ranging:
_ranging.DataIQ_swigregister(DataIQ)

class MusicData(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, _rows, _cols, _delta_F, _L):
        _ranging.MusicData_swiginit(self, _ranging.new_MusicData(_rows, _cols, _delta_F, _L))

    def rows(self):
        return _ranging.MusicData_rows(self)

    def cols(self):
        return _ranging.MusicData_cols(self)

    def reset(self):
        return _ranging.MusicData_reset(self)
    hest = property(_ranging.MusicData_hest_get, _ranging.MusicData_hest_set)
    EigenVects = property(_ranging.MusicData_EigenVects_get, _ranging.MusicData_EigenVects_set)
    EigenValues = property(_ranging.MusicData_EigenValues_get, _ranging.MusicData_EigenValues_set)
    delta_F = property(_ranging.MusicData_delta_F_get)
    L = property(_ranging.MusicData_L_get)
    __swig_destroy__ = _ranging.delete_MusicData

# Register MusicData in _ranging:
_ranging.MusicData_swigregister(MusicData)

ALGO_TYPE_EVD = _ranging.ALGO_TYPE_EVD
ALGO_TYPE_EIGEN_SAES = _ranging.ALGO_TYPE_EIGEN_SAES
class Worker(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def crNonPhaseCoherent(self, m):
        return _ranging.Worker_crNonPhaseCoherent(self, m)

    def calculateCrNonPhaseCoherent(self, m, delta_F, L):
        return _ranging.Worker_calculateCrNonPhaseCoherent(self, m, delta_F, L)

    def crPhaseCoherent(self, m):
        return _ranging.Worker_crPhaseCoherent(self, m)

    def calculateCrPhaseCoherent(self, m, delta_F, L):
        return _ranging.Worker_calculateCrPhaseCoherent(self, m, delta_F, L)

    def calculateDistance(self, m, evdType=0):
        return _ranging.Worker_calculateDistance(self, m, evdType)

    def showSettings(self):
        return _ranging.Worker_showSettings(self)
    settings = property(_ranging.Worker_settings_get, _ranging.Worker_settings_set)

    def __init__(self):
        _ranging.Worker_swiginit(self, _ranging.new_Worker())
    __swig_destroy__ = _ranging.delete_Worker

# Register Worker in _ranging:
_ranging.Worker_swigregister(Worker)

class RangingSettings(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self):
        _ranging.RangingSettings_swiginit(self, _ranging.new_RangingSettings())

    def defaults(self):
        return _ranging.RangingSettings_defaults(self)
    PS_approx = property(_ranging.RangingSettings_PS_approx_get, _ranging.RangingSettings_PS_approx_set)
    InitPos = property(_ranging.RangingSettings_InitPos_get, _ranging.RangingSettings_InitPos_set)
    MinLevel = property(_ranging.RangingSettings_MinLevel_get, _ranging.RangingSettings_MinLevel_set)
    TOL1 = property(_ranging.RangingSettings_TOL1_get, _ranging.RangingSettings_TOL1_set)
    TOL2 = property(_ranging.RangingSettings_TOL2_get, _ranging.RangingSettings_TOL2_set)
    NFFT = property(_ranging.RangingSettings_NFFT_get, _ranging.RangingSettings_NFFT_set)
    maxiter = property(_ranging.RangingSettings_maxiter_get, _ranging.RangingSettings_maxiter_set)
    MethodSubspaceSep = property(_ranging.RangingSettings_MethodSubspaceSep_get, _ranging.RangingSettings_MethodSubspaceSep_set)
    __swig_destroy__ = _ranging.delete_RangingSettings

# Register RangingSettings in _ranging:
_ranging.RangingSettings_swigregister(RangingSettings)



