#------------------------------------------------------------------------------
# Copyright : Stichting imec Nederland (http://www.imec.nl)
#             *** IMEC CONFIDENTIAL ***
#------------------------------------------------------------------------------

# Form implementation generated from reading ui file 'gui_designs\gui_multi_anchor_localization.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/figures/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_bckgrd = QtWidgets.QFrame(self.centralwidget)
        self.frame_bckgrd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_bckgrd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bckgrd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bckgrd.setObjectName("frame_bckgrd")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_bckgrd)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_imec_logo = QtWidgets.QFrame(self.frame_bckgrd)
        self.frame_imec_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imec_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imec_logo.setObjectName("frame_imec_logo")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_imec_logo)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_logo_jade = QtWidgets.QLabel(self.frame_imec_logo)
        self.label_logo_jade.setMinimumSize(QtCore.QSize(200, 60))
        self.label_logo_jade.setMaximumSize(QtCore.QSize(200, 60))
        self.label_logo_jade.setStyleSheet("")
        self.label_logo_jade.setText("")
        self.label_logo_jade.setPixmap(QtGui.QPixmap(":/Figures/figures/imec-logo_200x60.png"))
        self.label_logo_jade.setObjectName("label_logo_jade")
        self.gridLayout_3.addWidget(self.label_logo_jade, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_imec_logo, 0, 0, 1, 1)
        self.frame_title = QtWidgets.QFrame(self.frame_bckgrd)
        self.frame_title.setMinimumSize(QtCore.QSize(800, 0))
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.label_title = QtWidgets.QLabel(self.frame_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAutoFillBackground(False)
        self.label_title.setStyleSheet("color: rgb(144, 41, 141);")
        self.label_title.setTextFormat(QtCore.Qt.PlainText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_title, 0, 1, 1, 1)
        self.frame_data1 = QtWidgets.QFrame(self.frame_bckgrd)
        self.frame_data1.setMinimumSize(QtCore.QSize(220, 0))
        self.frame_data1.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_data1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_data1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_data1.setObjectName("frame_data1")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_data1)
        self.gridLayout.setObjectName("gridLayout")
        self.line_2 = QtWidgets.QFrame(self.frame_data1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 1)
        self.x_axis_display_layout = QtWidgets.QHBoxLayout()
        self.x_axis_display_layout.setObjectName("x_axis_display_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.x_axis_display_layout.addItem(spacerItem2)
        self.lcdNumber_position_x = QtWidgets.QLCDNumber(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_position_x.sizePolicy().hasHeightForWidth())
        self.lcdNumber_position_x.setSizePolicy(sizePolicy)
        self.lcdNumber_position_x.setMinimumSize(QtCore.QSize(170, 70))
        self.lcdNumber_position_x.setMaximumSize(QtCore.QSize(170, 70))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.lcdNumber_position_x.setFont(font)
        self.lcdNumber_position_x.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcdNumber_position_x.setSmallDecimalPoint(True)
        self.lcdNumber_position_x.setDigitCount(4)
        self.lcdNumber_position_x.setMode(QtWidgets.QLCDNumber.Oct)
        self.lcdNumber_position_x.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_position_x.setProperty("value", 0.0)
        self.lcdNumber_position_x.setProperty("intValue", 0)
        self.lcdNumber_position_x.setObjectName("lcdNumber_position_x")
        self.x_axis_display_layout.addWidget(self.lcdNumber_position_x)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.x_axis_display_layout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.x_axis_display_layout, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 17, 0, 1, 1)
        self.y_axis_display_layout = QtWidgets.QHBoxLayout()
        self.y_axis_display_layout.setObjectName("y_axis_display_layout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.y_axis_display_layout.addItem(spacerItem5)
        self.lcdNumber_position_y = QtWidgets.QLCDNumber(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_position_y.sizePolicy().hasHeightForWidth())
        self.lcdNumber_position_y.setSizePolicy(sizePolicy)
        self.lcdNumber_position_y.setMinimumSize(QtCore.QSize(170, 70))
        self.lcdNumber_position_y.setMaximumSize(QtCore.QSize(170, 70))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.lcdNumber_position_y.setFont(font)
        self.lcdNumber_position_y.setSmallDecimalPoint(True)
        self.lcdNumber_position_y.setDigitCount(4)
        self.lcdNumber_position_y.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber_position_y.setProperty("value", 0.0)
        self.lcdNumber_position_y.setProperty("intValue", 0)
        self.lcdNumber_position_y.setObjectName("lcdNumber_position_y")
        self.y_axis_display_layout.addWidget(self.lcdNumber_position_y)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.y_axis_display_layout.addItem(spacerItem6)
        self.gridLayout.addLayout(self.y_axis_display_layout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.label_ranging_quality = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ranging_quality.sizePolicy().hasHeightForWidth())
        self.label_ranging_quality.setSizePolicy(sizePolicy)
        self.label_ranging_quality.setMinimumSize(QtCore.QSize(0, 0))
        self.label_ranging_quality.setMaximumSize(QtCore.QSize(125, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.label_ranging_quality.setFont(font)
        self.label_ranging_quality.setAutoFillBackground(False)
        self.label_ranging_quality.setTextFormat(QtCore.Qt.PlainText)
        self.label_ranging_quality.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_ranging_quality.setObjectName("label_ranging_quality")
        self.horizontalLayout_2.addWidget(self.label_ranging_quality)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.likeliness_textEdit_brd5 = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.likeliness_textEdit_brd5.sizePolicy().hasHeightForWidth())
        self.likeliness_textEdit_brd5.setSizePolicy(sizePolicy)
        self.likeliness_textEdit_brd5.setMinimumSize(QtCore.QSize(80, 0))
        self.likeliness_textEdit_brd5.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.likeliness_textEdit_brd5.setFont(font)
        self.likeliness_textEdit_brd5.setAcceptDrops(False)
        self.likeliness_textEdit_brd5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.likeliness_textEdit_brd5.setStyleSheet("")
        self.likeliness_textEdit_brd5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.likeliness_textEdit_brd5.setLineWidth(0)
        self.likeliness_textEdit_brd5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.likeliness_textEdit_brd5.setReadOnly(True)
        self.likeliness_textEdit_brd5.setAcceptRichText(True)
        self.likeliness_textEdit_brd5.setObjectName("likeliness_textEdit_brd5")
        self.horizontalLayout_9.addWidget(self.likeliness_textEdit_brd5)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.progressBar_brd5 = QtWidgets.QProgressBar(self.frame_data1)
        self.progressBar_brd5.setMinimumSize(QtCore.QSize(110, 20))
        self.progressBar_brd5.setMaximumSize(QtCore.QSize(115, 20))
        self.progressBar_brd5.setProperty("value", 0)
        self.progressBar_brd5.setTextVisible(False)
        self.progressBar_brd5.setInvertedAppearance(False)
        self.progressBar_brd5.setObjectName("progressBar_brd5")
        self.horizontalLayout_9.addWidget(self.progressBar_brd5)
        self.gridLayout.addLayout(self.horizontalLayout_9, 10, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.likeliness_textEdit_brd2 = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.likeliness_textEdit_brd2.sizePolicy().hasHeightForWidth())
        self.likeliness_textEdit_brd2.setSizePolicy(sizePolicy)
        self.likeliness_textEdit_brd2.setMinimumSize(QtCore.QSize(80, 0))
        self.likeliness_textEdit_brd2.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.likeliness_textEdit_brd2.setFont(font)
        self.likeliness_textEdit_brd2.setAcceptDrops(False)
        self.likeliness_textEdit_brd2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.likeliness_textEdit_brd2.setStyleSheet("")
        self.likeliness_textEdit_brd2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.likeliness_textEdit_brd2.setLineWidth(0)
        self.likeliness_textEdit_brd2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.likeliness_textEdit_brd2.setReadOnly(True)
        self.likeliness_textEdit_brd2.setAcceptRichText(True)
        self.likeliness_textEdit_brd2.setObjectName("likeliness_textEdit_brd2")
        self.horizontalLayout_6.addWidget(self.likeliness_textEdit_brd2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.progressBar_brd2 = QtWidgets.QProgressBar(self.frame_data1)
        self.progressBar_brd2.setMinimumSize(QtCore.QSize(110, 20))
        self.progressBar_brd2.setMaximumSize(QtCore.QSize(115, 20))
        self.progressBar_brd2.setProperty("value", 0)
        self.progressBar_brd2.setTextVisible(False)
        self.progressBar_brd2.setInvertedAppearance(False)
        self.progressBar_brd2.setObjectName("progressBar_brd2")
        self.horizontalLayout_6.addWidget(self.progressBar_brd2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.likeliness_textEdit_brd4 = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.likeliness_textEdit_brd4.sizePolicy().hasHeightForWidth())
        self.likeliness_textEdit_brd4.setSizePolicy(sizePolicy)
        self.likeliness_textEdit_brd4.setMinimumSize(QtCore.QSize(80, 0))
        self.likeliness_textEdit_brd4.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.likeliness_textEdit_brd4.setFont(font)
        self.likeliness_textEdit_brd4.setAcceptDrops(False)
        self.likeliness_textEdit_brd4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.likeliness_textEdit_brd4.setStyleSheet("")
        self.likeliness_textEdit_brd4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.likeliness_textEdit_brd4.setLineWidth(0)
        self.likeliness_textEdit_brd4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.likeliness_textEdit_brd4.setReadOnly(True)
        self.likeliness_textEdit_brd4.setAcceptRichText(True)
        self.likeliness_textEdit_brd4.setObjectName("likeliness_textEdit_brd4")
        self.horizontalLayout_8.addWidget(self.likeliness_textEdit_brd4)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.progressBar_brd4 = QtWidgets.QProgressBar(self.frame_data1)
        self.progressBar_brd4.setMinimumSize(QtCore.QSize(110, 20))
        self.progressBar_brd4.setMaximumSize(QtCore.QSize(115, 20))
        self.progressBar_brd4.setProperty("value", 0)
        self.progressBar_brd4.setTextVisible(False)
        self.progressBar_brd4.setInvertedAppearance(False)
        self.progressBar_brd4.setObjectName("progressBar_brd4")
        self.horizontalLayout_8.addWidget(self.progressBar_brd4)
        self.gridLayout.addLayout(self.horizontalLayout_8, 9, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame_data1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 11, 0, 1, 1)
        self.pos_x_layout_name = QtWidgets.QHBoxLayout()
        self.pos_x_layout_name.setObjectName("pos_x_layout_name")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.pos_x_layout_name.addItem(spacerItem12)
        self.label_position_x = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_position_x.sizePolicy().hasHeightForWidth())
        self.label_position_x.setSizePolicy(sizePolicy)
        self.label_position_x.setMinimumSize(QtCore.QSize(100, 24))
        self.label_position_x.setMaximumSize(QtCore.QSize(300, 24))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.label_position_x.setFont(font)
        self.label_position_x.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_position_x.setTextFormat(QtCore.Qt.PlainText)
        self.label_position_x.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_position_x.setObjectName("label_position_x")
        self.pos_x_layout_name.addWidget(self.label_position_x)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.pos_x_layout_name.addItem(spacerItem13)
        self.gridLayout.addLayout(self.pos_x_layout_name, 0, 0, 1, 1)
        self.exit_button_layout = QtWidgets.QHBoxLayout()
        self.exit_button_layout.setObjectName("exit_button_layout")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.exit_button_layout.addItem(spacerItem14)
        self.btnExit = QtWidgets.QPushButton(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setMinimumSize(QtCore.QSize(159, 55))
        self.btnExit.setMaximumSize(QtCore.QSize(159, 55))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnExit.setFont(font)
        self.btnExit.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/figures/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon1)
        self.btnExit.setObjectName("btnExit")
        self.exit_button_layout.addWidget(self.btnExit)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.exit_button_layout.addItem(spacerItem15)
        self.gridLayout.addLayout(self.exit_button_layout, 15, 0, 1, 1)
        self.pos_y_layout_name = QtWidgets.QHBoxLayout()
        self.pos_y_layout_name.setObjectName("pos_y_layout_name")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.pos_y_layout_name.addItem(spacerItem16)
        self.label_position_y = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_position_y.sizePolicy().hasHeightForWidth())
        self.label_position_y.setSizePolicy(sizePolicy)
        self.label_position_y.setMinimumSize(QtCore.QSize(100, 24))
        self.label_position_y.setMaximumSize(QtCore.QSize(300, 24))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.label_position_y.setFont(font)
        self.label_position_y.setAutoFillBackground(False)
        self.label_position_y.setTextFormat(QtCore.Qt.PlainText)
        self.label_position_y.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_position_y.setObjectName("label_position_y")
        self.pos_y_layout_name.addWidget(self.label_position_y)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.pos_y_layout_name.addItem(spacerItem17)
        self.gridLayout.addLayout(self.pos_y_layout_name, 2, 0, 1, 1)
        self.circle_trust_layout = QtWidgets.QHBoxLayout()
        self.circle_trust_layout.setObjectName("circle_trust_layout")
        self.circleoftrust_label = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circleoftrust_label.sizePolicy().hasHeightForWidth())
        self.circleoftrust_label.setSizePolicy(sizePolicy)
        self.circleoftrust_label.setMinimumSize(QtCore.QSize(105, 25))
        self.circleoftrust_label.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.circleoftrust_label.setFont(font)
        self.circleoftrust_label.setObjectName("circleoftrust_label")
        self.circle_trust_layout.addWidget(self.circleoftrust_label)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.circle_trust_layout.addItem(spacerItem18)
        self.circleoftrust_led = QtWidgets.QHBoxLayout()
        self.circleoftrust_led.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.circleoftrust_led.setSpacing(6)
        self.circleoftrust_led.setObjectName("circleoftrust_led")
        self.circle_trust_layout.addLayout(self.circleoftrust_led)
        self.gridLayout.addLayout(self.circle_trust_layout, 13, 0, 1, 1)
        self.start_button_layout = QtWidgets.QHBoxLayout()
        self.start_button_layout.setObjectName("start_button_layout")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.start_button_layout.addItem(spacerItem19)
        self.btnStart = QtWidgets.QPushButton(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        self.btnStart.setMinimumSize(QtCore.QSize(159, 55))
        self.btnStart.setMaximumSize(QtCore.QSize(159, 55))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/figures/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/Icons/figures/Play.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/Icons/figures/Stop.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.btnStart.setIcon(icon2)
        self.btnStart.setObjectName("btnStart")
        self.start_button_layout.addWidget(self.btnStart)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.start_button_layout.addItem(spacerItem20)
        self.gridLayout.addLayout(self.start_button_layout, 14, 0, 1, 1)
        self.connection_layout = QtWidgets.QHBoxLayout()
        self.connection_layout.setObjectName("connection_layout")
        self.connection_label = QtWidgets.QLabel(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connection_label.sizePolicy().hasHeightForWidth())
        self.connection_label.setSizePolicy(sizePolicy)
        self.connection_label.setMinimumSize(QtCore.QSize(105, 25))
        self.connection_label.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(13)
        self.connection_label.setFont(font)
        self.connection_label.setObjectName("connection_label")
        self.connection_layout.addWidget(self.connection_label)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connection_layout.addItem(spacerItem21)
        self.connection_led = QtWidgets.QHBoxLayout()
        self.connection_led.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.connection_led.setSpacing(0)
        self.connection_led.setObjectName("connection_led")
        self.connection_layout.addLayout(self.connection_led)
        self.gridLayout.addLayout(self.connection_layout, 12, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.likeliness_textEdit_brd1 = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.likeliness_textEdit_brd1.sizePolicy().hasHeightForWidth())
        self.likeliness_textEdit_brd1.setSizePolicy(sizePolicy)
        self.likeliness_textEdit_brd1.setMinimumSize(QtCore.QSize(80, 0))
        self.likeliness_textEdit_brd1.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.likeliness_textEdit_brd1.setFont(font)
        self.likeliness_textEdit_brd1.setAcceptDrops(False)
        self.likeliness_textEdit_brd1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.likeliness_textEdit_brd1.setStyleSheet("")
        self.likeliness_textEdit_brd1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.likeliness_textEdit_brd1.setLineWidth(0)
        self.likeliness_textEdit_brd1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.likeliness_textEdit_brd1.setReadOnly(True)
        self.likeliness_textEdit_brd1.setAcceptRichText(True)
        self.likeliness_textEdit_brd1.setObjectName("likeliness_textEdit_brd1")
        self.horizontalLayout.addWidget(self.likeliness_textEdit_brd1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem22)
        self.progressBar_brd1 = QtWidgets.QProgressBar(self.frame_data1)
        self.progressBar_brd1.setMinimumSize(QtCore.QSize(110, 20))
        self.progressBar_brd1.setMaximumSize(QtCore.QSize(115, 20))
        self.progressBar_brd1.setProperty("value", 0)
        self.progressBar_brd1.setTextVisible(False)
        self.progressBar_brd1.setInvertedAppearance(False)
        self.progressBar_brd1.setObjectName("progressBar_brd1")
        self.horizontalLayout.addWidget(self.progressBar_brd1)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.likeliness_textEdit_brd3 = QtWidgets.QTextEdit(self.frame_data1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.likeliness_textEdit_brd3.sizePolicy().hasHeightForWidth())
        self.likeliness_textEdit_brd3.setSizePolicy(sizePolicy)
        self.likeliness_textEdit_brd3.setMinimumSize(QtCore.QSize(80, 0))
        self.likeliness_textEdit_brd3.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.likeliness_textEdit_brd3.setFont(font)
        self.likeliness_textEdit_brd3.setAcceptDrops(False)
        self.likeliness_textEdit_brd3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.likeliness_textEdit_brd3.setStyleSheet("")
        self.likeliness_textEdit_brd3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.likeliness_textEdit_brd3.setLineWidth(0)
        self.likeliness_textEdit_brd3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.likeliness_textEdit_brd3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.likeliness_textEdit_brd3.setReadOnly(True)
        self.likeliness_textEdit_brd3.setAcceptRichText(True)
        self.likeliness_textEdit_brd3.setObjectName("likeliness_textEdit_brd3")
        self.horizontalLayout_7.addWidget(self.likeliness_textEdit_brd3)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem23)
        self.progressBar_brd3 = QtWidgets.QProgressBar(self.frame_data1)
        self.progressBar_brd3.setMinimumSize(QtCore.QSize(110, 20))
        self.progressBar_brd3.setMaximumSize(QtCore.QSize(115, 20))
        self.progressBar_brd3.setProperty("value", 0)
        self.progressBar_brd3.setTextVisible(False)
        self.progressBar_brd3.setInvertedAppearance(False)
        self.progressBar_brd3.setObjectName("progressBar_brd3")
        self.horizontalLayout_7.addWidget(self.progressBar_brd3)
        self.gridLayout.addLayout(self.horizontalLayout_7, 8, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_data1, 1, 0, 1, 1)
        self.MplWidget = MplWidget(self.frame_bckgrd)
        self.MplWidget.setMinimumSize(QtCore.QSize(800, 450))
        self.MplWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MplWidget.setStyleSheet("")
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout_4.addWidget(self.MplWidget, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_bckgrd, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "imec - Passive keyless entry using Bluetooth"))
        self.label_title.setText(_translate("MainWindow", "High accuracy phase-based multi-device localization"))
        self.label_ranging_quality.setText(_translate("MainWindow", "Ranging Quality"))
        self.likeliness_textEdit_brd5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.likeliness_textEdit_brd2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.likeliness_textEdit_brd4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.label_position_x.setText(_translate("MainWindow", "Position x (m)"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
        self.label_position_y.setText(_translate("MainWindow", "Position y (m)"))
        self.circleoftrust_label.setText(_translate("MainWindow", "Inside CoT"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.connection_label.setText(_translate("MainWindow", "Connection"))
        self.likeliness_textEdit_brd1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.likeliness_textEdit_brd3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
from mplwidget import MplWidget
import gui_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
